#!/usr/bin/env zsh

for file in $@
do
	text=$(cat $file)
	if (( $(echo $text | wc -l) == 1 )) && [[ $text == "http"* ]] && [[ $text != *" "* ]]
	then
		echo $text
		echo '[InternetShortcut]\nURL='$text > $file
		mv "$file" "${file%.txt}.URL" --no-clobber
	elif (( $(echo $text | wc -l) == 1 )) && [[ $text == *"http"* ]]
	then
		text_split=$(echo $text | sed -E 's/\s+http/\nhttp/g')
		if (( $(echo $text_split | wc -l) == 2 ))
		then
			text=$(echo $text_split | sed '1q;d' | sed 's/[|]/｜/g; s/[:]/：/g; s/[?]/？/g')
			url=$(echo $text_split | sed '2q;d')
			if [[ $url != *" "* ]]
			then
				echo $text
				echo $url
				echo '[InternetShortcut]\nURL='$url'\nDESC='$text > $file
				mv "$file" "${file%.txt} ${text}.URL" -v --no-clobber
			fi
		fi
	else
		echo SKIPPED
		echo $text
	fi
	echo "----"
done