#!/usr/bin/env bash

if [ "$*" == "" ]
then
	cat "$0"

elif [ "$*" == "show size" ]
then
	# https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Individual_packages
	LC_ALL=C pacman -Qi | awk '/^Name/{name=$3} /^Installed Size/{print $4$5, name}' | sort -h

elif [ "$*" == "show size manual" ]
then
	LC_ALL=C pacman -Qei | awk '/^Name/{name=$3} /^Installed Size/{print $4$5, name}' | sort -h

elif [ "$*" == "del cache" ]
then
	sudo pacman -Sc
	paccache --cachedir "$(dirname "$(aur repo -d custom --path)")" -vvv --remove --keep 1
	paccache --cachedir "$(dirname "$(aur repo -d custom-gdfuse --path)")" -vvv --remove --keep 1

elif [ "$*" == "del orphan" ]
then
	pacman -Qqdtt
	sudo pacman -Rs $(pacman -Qqdtt)

elif [ "$*" == "del aur old" ]
then
	cull_list=$(LANG=C pacman -Sl custom custom-gdfuse | grep --invert-match installed | cut -d' ' -f2 --output-delimiter=' ')
	echo "$cull_list"
	for pkg in $cull_list
	do
		aur remove "$pkg"
	done
	sudo pacman -Sy

fi