#!/usr/bin/env bash

case "$*" in
"")
	cat "$0"
	;;
"show size")
	# https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Individual_packages
	LC_ALL=C pacman -Qi | awk '/^Name/{name=$3} /^Installed Size/{print $4$5, name}' | sort -h
	;;
"show size dep")
	LC_ALL=C pacman -Qdi | awk '/^Name/{name=$3} /^Required By/{rby=$4} /^Installed Size/{print $4$5, name, '\t' ,rby}' | sort -h
	;;
"show size exp")
	LC_ALL=C pacman -Qei | awk '/^Name/{name=$3} /^Installed Size/{print $4$5, name}' | sort -h
	;;
"del cache")
	sudo pacman -Scc
	paccache --cachedir "$(dirname "$(aur repo -d custom --path)")" -vvv --remove --keep 1
	paccache --cachedir "$(dirname "$(aur repo -d custom-gdfuse --path)")" -vvv --remove --keep 1
	;;
"del orphan")
	pacman -Qqdtt
	sudo pacman -Rs $(pacman -Qqdtt)
	;;
"del aur old")
	cull_list=$(LANG=C pacman -Sl custom custom-gdfuse | grep --invert-match installed | cut -d' ' -f2 --output-delimiter=' ')
	echo "$cull_list"
	for pkg in $cull_list
	do
		aur remove "$pkg"
	done
	sudo pacman -Sy
	;;
esac