#!/usr/bin/env python
import numpy as np
import sys
text = sys.stdin.read()
for chunk in reversed(text.split('\n\n')):
	print()
	print('\n'.join([''.join(row) for row in np.rot90([list(row) for row in chunk.strip().split('\n')])]))