#!/usr/bin/env python

# https://stackoverflow.com/questions/3438756/some-built-in-to-pad-a-list-in-python
# https://stackoverflow.com/questions/8421337/rotating-a-two-dimensional-array-in-python

import sys
text = sys.stdin.read()
text = text.strip().split('\n')
text_lens = [len(line) for line in text]
text_lens_max = max(text_lens)
text = [list(line) + [''] * (text_lens_max - len(line)) for line in text]

print(
'\n'.join(reversed([''.join(row) for row in zip(*text[::1])]))
)